using ReactiveUI;
using System;
using System.IO;
using System.Reflection;

namespace AvaloniaApplication4.ViewModels
{
    public class SettingsPageViewModel : PageViewModelBase
    {
        private string _defaultSaveLocation;
        private string _defaultFileFormat;
        private int _qrCodeSize;
        private bool _autoGenerateEnabled;
        private double _autoGenerateDelay;

        public SettingsPageViewModel()
        {
            Title = "Settings";
            Icon = "⚙️";

            // Initialize with defaults
            _defaultSaveLocation = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            _defaultFileFormat = ".jpg";
            _qrCodeSize = 20;
            _autoGenerateEnabled = true;
            _autoGenerateDelay = 0.5;
        }

        public string DefaultSaveLocation
        {
            get => _defaultSaveLocation;
            set => this.RaiseAndSetIfChanged(ref _defaultSaveLocation, value);
        }

        public string DefaultFileFormat
        {
            get => _defaultFileFormat;
            set => this.RaiseAndSetIfChanged(ref _defaultFileFormat, value);
        }

        public int QrCodeSize
        {
            get => _qrCodeSize;
            set => this.RaiseAndSetIfChanged(ref _qrCodeSize, value);
        }

        public bool AutoGenerateEnabled
        {
            get => _autoGenerateEnabled;
            set => this.RaiseAndSetIfChanged(ref _autoGenerateEnabled, value);
        }

        public double AutoGenerateDelay
        {
            get => _autoGenerateDelay;
            set => this.RaiseAndSetIfChanged(ref _autoGenerateDelay, value);
        }

        public string AppVersion => Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "1.0.0";
    }
}
